env:
  browser: true
  es2021: true
  node: true
overrides: 
  - files: ["*.svelte"]
    parser: "svelte-eslint-parser"
    extends: ["plugin:svelte/prettier"]
    rules: 
      prettier/prettier': off
extends: 
  - eslint:recommended
  - plugin:svelte/prettier
  - prettier
  - plugin:prettier/recommended
plugins:
  - prettier
  - svelte
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier:
    - error
  eqeqeq: 
    - error
    - always
  no-constant-condition:
    - off
  prefer-const: 
    - error
  no-fallthrough: 
    - off
  no-async-promise-executor:
    - off