env:
  browser: true
  es2021: true
  node: true
extends: 
  - eslint:recommended
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier:
    - error
  indent:
    - error
    - 2
    - 
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  eqeqeq: 
    - error
    - always
