import { SECOND } from '#src/constants/time.js'

export const MESSAGES_SPAM_FILTER_TARGET_ALWAYS = 2 * SECOND
export const MESSAGES_SPAM_FILTER_TARGET_WHEN_PASSED = 8 * SECOND
export const MESSAGES_SPAM_FILTER_ALLOWED_IN_SUCCESSION = 60
