export const LEVELINCREASE_EXPERIENCE_PER_LEVEL = 45;
export const MESSAGES_SPAM_FILTER_TARGET_ALWAYS = 2_000;
export const MESSAGES_SPAM_FILTER_TARGET_WHEN_PASSED = 8_000;
export const MESSAGES_SPAM_FILTER_ALLOWED_IN_SUCCESSION = 60;
