import * as Util from "#lib/util.js";

const Schema = {
  Bot: {
    berrysPrice: 0,
    grempenItems: "",
  },
  Guild: {
    name: "",
    boss: {
      users: [
        {
          userStats: {},
        },
      ],
    },
  },
  User: {
    id: "",
    name: "",
    coins: 0,
    level: 0,
    exp: 0,
    berrys: 0,
    chestLevel: 0,
    void: 0,
    keys: 0,
    voidRituals: 0,
    voidCoins: 0,
    quest: {
      id: "",
      goal: 0,
      progress: 0,
      reward: 0,
      day: 0,
      willUpdated: true,
      isCompleted: true,
    },
    curses: [
      {
        id: "",
        values: {
          goal: 0,
          progress: 0,
          timer: 0,
        },
        timestamp: 0,
      },
    ],
    questReward: {},
    questTime: {},
    last_online: 0,
    chestBonus: 0,
    praiseMe: [""],
    BDay: "",
    questsGlobalCompleted: {},
    grempenBoughted: 0,
    shopTime: {},
    first_$: true,
    praise: [""],
    profile_color: {},
    profile_description: {},
    questLast: {},
    dayQuests: {},
    thiefGloves: {},
    chilli: {},
    invites: {},
    iq: 0,
    cursesEnded: 0,
    voidCasino: {},
    element: {},
    coinsPerMessage: 0,
    voidPrice: {},
    elementLevel: 0,
    bag: {},
    seed: 0,
    voidTreeFarm: {},
    voidDouble: {},
    CD_$: 0,
    leave_roles: {},
    profile_confidentiality: {},
    voidQuests: {},
    monster: {},
    monstersBought: {},
    voidThief: {},
    thiefWins: {},
    voidMysticClover: {},
    voidFreedomCurse: {},
    voidCooldown: {},
    remainedQuest: {},
    bossEffects: {},
    bossEffectsCallbackMap: {},
    cursesCallbackMap: {},
  },
  curseEntity: {},

  timeEventEntity: {},
  counterEntity: {},
};

const ProperiesList = {
  berrysPrice: {},
  grempen: {},

  name: {},
  id: {},
  coins: {
    label: "Коин",
    labelMeta: {
      base: "коин",
      suffixes: ["ов", "", "а"],
    },
  },
  level: {},
  exp: {},
  berrys: {},
  chestLevel: {},
  void: {},
  keys: {
    label: "Ключ",
    labelMeta: {
      base: "ключ",
      suffixes: ["ей", "", "а"],
    },
  },
  voidRituals: {},
  voidCoins: {},
  questProgress: {},
  questNeed: {},
  questReward: {},
  questTime: {},
  last_online: {},
  chestBonus: {},
  praiseMe: {},
  BDay: {},
  questsGlobalCompleted: {},
  shopTime: {},
  first_$: {},
  praise: {},
  profile_color: {},
  profile_description: {},
  questLast: {},
  dayQuests: {},
  thiefGloves: {},
  chilli: {},
  invites: {},
  iq: {},
  cursesEnded: {},
  voidCasino: {},
  element: {},
  coinsPerMessage: {},
  voidPrice: {},
  elementLevel: {},
  bag: {},
  curses: {},
  seed: {},
  voidTreeFarm: {},
  voidDouble: {},
  CD_$: {},
  leave_roles: {},
  profile_confidentiality: {},
  voidQuests: {},
  monster: 0,
  monstersBought: 0,
  voidThief: {},
  thiefWins: {},
  quest: {},
  voidMysticClover: {},
  voidFreedomCurse: {},
  chestbonus: {},
  voidCooldown: {},
  remainedQuest: {},
  bossEffects: {},
  bossEffectsCallbackMap: {},
  cursesCallbackMap: {},
};

const PropertiesEnum = {
  berrysPrice: "berrysPrice",
  grempen: "grempen",
  name: "name",
  id: "id",
  coins: "coins",
  level: "level",
  exp: "exp",
  berrys: "berrys",
  chestLevel: "chestLevel",
  void: "void",
  keys: "keys",
  voidRituals: "voidRituals",
  voidCoins: "voidCoins",
  questProgress: "questProgress",
  questNeed: "questNeed",
  questReward: "questReward",
  questTime: "questTime",
  last_online: "last_online",
  chestBonus: "chestBonus",
  praiseMe: "praiseMe",
  BDay: "BDay",
  questsGlobalCompleted: "questsGlobalCompleted",
  shopTime: "shopTime",
  first_$: "first_$",
  praise: "praise",
  profile_color: "profile_color",
  profile_description: "profile_description",
  questLast: "questLast",
  dayQuests: "dayQuests",
  thiefGloves: "thiefGloves",
  chilli: "chilli",
  invites: "invites",
  iq: "iq",
  cursesEnded: "cursesEnded",
  voidCasino: "voidCasino",
  element: "element",
  coinsPerMessage: "coinsPerMessage",
  voidPrice: "voidPrice",
  elementLevel: "elementLevel",
  bag: "bag",
  curses: "curses",
  seed: "seed",
  voidTreeFarm: "voidTreeFarm",
  voidDouble: "voidDouble",
  CD_$: "CD_$",
  leave_roles: "leave_roles",
  profile_confidentiality: "profile_confidentiality",
  voidQuests: "voidQuests",
  monster: "monster",
  monstersBought: "monstersBought",
  voidThief: "voidThief",
  thiefWins: "thiefWins",
  quest: "quest",
  voidMysticClover: "voidMysticClover",
  voidFreedomCurse: "voidFreedomCurse",
  chestbonus: "chestbonus",
  voidCooldown: "voidCooldown",
  remainedQuest: "remainedQuest",
  bossEffects: "bossEffects",
  bossEffectsCallbackMap: "bossEffectsCallbackMap",
  cursesCallbackMap: "cursesCallbackMap",
};

class Properties {
  static endingOf(property, quantity) {
    const item = ProperiesList[property];
    if (!item) {
      return undefined;
    }

    const { labelMeta } = item;
    if (!labelMeta) {
      return `${quantity} ${item.label}`;
    }

    return Util.ending(quantity, labelMeta.base, ...labelMeta.suffixes, {
      unite: (_, word) => word,
    });
  }

  static emojiOf(propertyBase) {
    return propertyBase.emoji;
  }
}

export { Properties, PropertiesEnum, ProperiesList, Schema };
export default Properties;
